# Generated by Django 6.0.7 on 2026-07-15 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PANEL', 'Panel Solar'), ('INVERSOR', 'Inversor Híbrido'), ('BATERIA', 'Banco de Baterías'), ('TABLERO', 'Componente de Tablero (Protecciones)')], max_length=20, verbose_name='Categoría')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('foto_real', models.ImageField(blank=True, null=True, upload_to='equipos/', verbose_name='Foto del Equipo Real')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta ($)')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateField(verbose_name='Fecha de Ejecución del Proyecto')),
                ('costo_materiales', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Materiales ($)')),
                ('mano_de_obra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mano de Obra ($)')),
                ('monto_total_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Cobrado al Cliente ($)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente', verbose_name='Cliente')),
                ('equipos', models.ManyToManyField(to='gestion.productoreal', verbose_name='Equipos a Instalar')),
            ],
        ),
    ]
