# Generated by Django 6.0.7 on 2026-07-16 02:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('identificacion_fiscal', models.CharField(max_length=50, verbose_name='RIF / NIT / RUT')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logotipo de la Empresa')),
            ],
            options={
                'verbose_name': 'Datos de mi Empresa',
                'verbose_name_plural': 'Datos de mi Empresa',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Existencia Actual')),
                ('stock_minimo', models.IntegerField(default=5)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ultimo Precio Costo')),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='costo_materiales',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='fecha_ejecucion',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='mano_de_obra',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='monto_total_cobrado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Notas / Descripción del Avance'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente / Planificado'), ('PROG', 'En Progreso'), ('TERM', 'Terminado')], default='PEND', max_length=4),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='monto_cobrado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Cobrado al Cliente'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tecnico Asignado'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Título del Trabajo u Obra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente'),
        ),
        migrations.CreateModel(
            name='FotoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='trabajos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestion.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='GastoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Concepto del Gasto (Ej. Transporte, Almuerzos)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='gestion.trabajo', verbose_name='Obra / Trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORR', 'Borrador'), ('ENVI', 'Enviado al Cliente'), ('ACEP', 'Aceptado (Crear Obra)'), ('RECH', 'Rechazado')], default='BORR', max_length=4)),
                ('notas_adicionales', models.TextField(blank=True, null=True, verbose_name='Condiciones o Notas del Presupuesto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.presupuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto', verbose_name='Material / Servicio')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.proveedor', verbose_name='Proveedor Habitual'),
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_comprada', models.IntegerField(verbose_name='Cantidad que Entra')),
                ('costo_unitario_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario de Compra')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Factura / Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_inventario', to='gestion.producto')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.proveedor')),
            ],
            options={
                'verbose_name': 'Control de Compra / Ingreso',
                'verbose_name_plural': 'Control de Compras (Ingresos)',
            },
        ),
        migrations.DeleteModel(
            name='ProductoReal',
        ),
    ]
