# Generated by Django 6.0.7 on 2026-07-26 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_categoriatransaccion_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto / Factura')),
                ('monto_deuda', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total a Pagar')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Abonado')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PAGD', 'Pagado')], default='PEND', max_length=4, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
