# Generated by Django 6.0.7 on 2026-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_cuentaporcobrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nota_privada',
            field=models.TextField(blank=True, null=True, verbose_name='Nota Privada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rif_cedula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rif o Cédula'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='concepto',
            field=models.CharField(max_length=200, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('PAG', 'Pagado'), ('VENC', 'Vencido')], default='PEND', max_length=4, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='monto_cobrado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Abonado / Cobrado'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='monto_deuda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('PAG', 'Pagado'), ('VENC', 'Vencido')], default='PEND', max_length=4, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='monto_deuda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Deuda'),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='concepto',
            field=models.CharField(max_length=150, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('EGR', 'Egreso')], default='ING', max_length=3, verbose_name='Tipo de Movimiento'),
        ),
        migrations.DeleteModel(
            name='CategoriaTransaccion',
        ),
    ]
