# Generated by Django 6.0.7 on 2026-08-02 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_transaccion_categoria_cliente_direccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha y Hora de la Visita')),
                ('tipo', models.CharField(choices=[('GRATIS', 'Visita de Cortesía / Diagnóstico (Gratis)'), ('COBRADA', 'Visita Técnica Facturable')], default='GRATIS', max_length=10, verbose_name='Tipo de Visita')),
                ('monto_cobro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo / Cobro de Visita')),
                ('estado', models.CharField(choices=[('PEND', 'Programada'), ('PROC', 'En Proceso'), ('COMP', 'Completada / Finalizada'), ('CANC', 'Cancelada')], default='PEND', max_length=4, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Notas / Requerimiento en Sitio')),
                ('genera_trabajo', models.BooleanField(default=False, verbose_name='¿Derivó en Orden de Trabajo / Presupuesto?')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente', verbose_name='Cliente')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Agenda de Visita en Campo',
                'verbose_name_plural': 'Agenda de Visitas en Campo',
            },
        ),
    ]
